### ISSUE TITLE
flatJSON causing sort function to not work -client side.

### ISSUE THREAD

**Issue by jtrumbull** [djhvscf/bootstrap-table-flatJSON#3]
@djhvscf Hope serial issue reporting isn't a bad thing ;)

When using the `flatJSON` extension, sort functionality, on the client side, does not work.

jsFiddle example: https://jsfiddle.net/joeycakes/c2c56wbs/1/

I'm not sure of the importance of the order of [Line 31](https://github.com/djhvscf/bootstrap-table-flatJSON/blob/master/src/bootstrap-table-flatJSON.js#L31) and [Line 32](https://github.com/djhvscf/bootstrap-table-flatJSON/blob/master/src/bootstrap-table-flatJSON.js#L32) in the `initData()` method, but if reversed the issue seems to be resolved. However, i'm not familiar enough with what the super `BootstrapTable.initData()` method is doing to know what other variables to check.

jsFiddle example: https://jsfiddle.net/joeycakes/umrt6qLf/1/

**Comment by djhvscf** [comment]
ok, let me check

**Comment by jtrumbull** [comment]
Found the problem (and why the above comment is fixing the problem):

The [`BootstrapTable.initData()`](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L663) calls [`this.initSort()`](https://github.com/wenzhixin/bootstrap-table/blob/master/src/bootstrap-table.js#L684), at the end of the method. The extension is calling [`flatJSON()`](https://github.com/djhvscf/bootstrap-table-flatJSON/blob/master/src/bootstrap-table-flatJSON.js#L32) _after_ this -meaning `initSort()` is working with a JSON object, not the flattened key/value pairs. Since the sort function doesn't know what to do with plain objects, it is returning it's insertion order.

**Comment by djhvscf** [comment]
Merged!
